spring.application.name=api_toca_dos_peludos

# URL de conexão (ajuste o nome do banco após a barra)
spring.datasource.url=jdbc:postgresql://localhost:5432/toca_dos_peludos_db
spring.datasource.username=postgres
spring.datasource.password=sua_senha_aqui

# Configurações do Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# aponta para driver do Postgre
spring.datasource.url = jdbc:postgresql://localhost:5432/toca_peludos_db
spring.datasource.username = "postgres"
spring.datasource.password = "root"
spring.jpa.hibernate.ddl-auto = update
spring.jpa..properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect



